disabled_rules:
  - nesting
  - large_tuple
  - implicit_optional_initialization
  - multiple_closures_with_trailing_closure

line_length:
  warning: 200
  error: 300
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 60
    error: 70
  allowed_symbols: ["_"]
  excluded:
    - C
    - L
    - R
    - G
    - B
    - X
    - Y
    - Z

file_length:
  warning: 900
  error: 1100

type_body_length:
  warning: 400
  error: 650

function_body_length:
  warning: 120
  error: 160

function_parameter_count:
  warning: 9
  error: 12

cyclomatic_complexity:
  warning: 15
  error: 25

excluded:
  - build
  - docs
