name: SmartCellCounter
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: 16.0
  createIntermediateGroups: true
packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: 6.0.0
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 10.0.0
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS.git
    from: 7.0.0
settings:
  base:
    DEVELOPMENT_TEAM: ABCDE12345
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
    TARGETED_DEVICE_FAMILY: "1,2"
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0
    CODE_SIGN_STYLE: Automatic
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    Release:
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
      DEAD_CODE_STRIPPING: YES
      STRIP_INSTALLED_PRODUCT: YES
      OTHER_LDFLAGS: "$(inherited) -dead_strip"
      ENABLE_TESTABILITY: NO
      ENABLE_BITCODE: NO
      SWIFT_STRICT_CONCURRENCY: complete

targets:
  SmartCellCounter:
    type: application
    platform: iOS
    sources:
      - path: Sources/SmartCellCounter
    info:
      path: Sources/SmartCellCounter/Info.plist
      properties:
        CFBundleDisplayName: SmartCellCounter
        CFBundleIdentifier: com.example.SmartCellCounter
        UILaunchStoryboardName: ""
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        NSCameraUsageDescription: "Camera access is required to capture hemocytometer images."
        NSPhotoLibraryUsageDescription: "Photo library access is used to import images."
        NSPhotoLibraryAddUsageDescription: "Saving analysis results to Photos requires permission."
        NSUserTrackingUsageDescription: "Tracking is used only to personalize ads, if enabled."
        UIFileSharingEnabled: true
        LSSupportsOpeningDocumentsInPlace: true
        UIRequiredDeviceCapabilities: [camera]
        CFBundleURLTypes:
                  - CFBundleTypeRole: Editor
                    CFBundleURLSchemes:
                      - com.googleusercontent.apps.com.googleusercontent.apps.12646043017-b5ojc052qv978ja3t778drbrmb75c9il
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.SmartCellCounter
    dependencies:
      - package: GRDB
      - package: Firebase
        products: [FirebaseAuth, FirebaseAnalytics]
      - package: GoogleSignIn
        products: [GoogleSignIn, GoogleSignInSwift]

  SmartCellCounterTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/SmartCellCounterTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: SmartCellCounter

  SmartCellCounterUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: Tests/SmartCellCounterUITests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: SmartCellCounter
