name: iOS CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install XcodeGen
        run: |
          brew install xcodegen

      - name: Generate Xcode project
        run: xcodegen generate

      - name: Show Xcode version
        run: xcodebuild -version

      - name: List available simulators (debug)
        run: xcrun simctl list devicetypes

      - name: Build and Test (iOS Simulator)
        run: |
          set -euo pipefail
          # Try common device names to maximize compatibility
          DEST="platform=iOS Simulator,OS=latest,name=iPhone 15"
          xcodebuild -project SmartCellCounter.xcodeproj -scheme SmartCellCounter -destination "$DEST" -quiet test | xcpretty || {
            echo "Retrying on iPhone 14..."
            DEST="platform=iOS Simulator,OS=latest,name=iPhone 14"
            xcodebuild -project SmartCellCounter.xcodeproj -scheme SmartCellCounter -destination "$DEST" -quiet test | xcpretty
          }

