name: iOS CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: macos-15
    env:
      GIT_TERMINAL_PROMPT: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure GitHub auth for SPM
        run: |
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Install XcodeGen
        run: |
          brew install xcodegen

      - name: Generate Xcode project
        run: xcodegen generate

      - name: Show Xcode version
        run: xcodebuild -version

      - name: List available simulators (debug)
        run: xcrun simctl list devicetypes

      - name: Build and Test (iOS Simulator)
        run: |
          set -euo pipefail
          # Resolve SPM first (helps isolate dependency issues)
          xcodebuild -project SmartCellCounter.xcodeproj -scheme SmartCellCounter -resolvePackageDependencies

          # Pick an available simulator dynamically (prefer iPhone 16 Pro)
          echo "Selecting available iOS Simulator..."
          DEV_NAMES=("iPhone 16 Pro" "iPhone 16" "iPhone 16 Pro Max" "iPhone SE (3rd generation)")
          DEST=""
          for NAME in "${DEV_NAMES[@]}"; do
            if xcrun simctl list devices available | grep -q "$NAME"; then
              DEST="platform=iOS Simulator,name=$NAME"
              echo "Using simulator: $NAME"
              break
            fi
          done
          if [ -z "$DEST" ]; then
            echo "Falling back to Any iOS Simulator Device"
            DEST="platform=iOS Simulator"
          fi

          xcodebuild -project SmartCellCounter.xcodeproj \
            -scheme SmartCellCounter \
            -destination "$DEST" \
            -destination-timeout 300 \
            test
