platform :ios, '15.0'
require_relative '../node_modules/react-native/scripts/autolink-ios'

target 'SmartCellCounter' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )

  pod 'TensorFlowLiteSwift'
  pod 'TensorFlowLiteSwift/Metal'

  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
end
